// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	autocodesign "github.com/bitrise-io/go-xcode/autocodesign"
	certificateutil "github.com/bitrise-io/go-xcode/certificateutil"

	mock "github.com/stretchr/testify/mock"
)

// AssetWriter is an autogenerated mock type for the AssetWriter type
type AssetWriter struct {
	mock.Mock
}

// InstallCertificate provides a mock function with given fields: certificate
func (_m *AssetWriter) InstallCertificate(certificate certificateutil.CertificateInfoModel) error {
	ret := _m.Called(certificate)

	var r0 error
	if rf, ok := ret.Get(0).(func(certificateutil.CertificateInfoModel) error); ok {
		r0 = rf(certificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: codesignAssetsByDistributionType
func (_m *AssetWriter) Write(codesignAssetsByDistributionType map[autocodesign.DistributionType]autocodesign.AppCodesignAssets) error {
	ret := _m.Called(codesignAssetsByDistributionType)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[autocodesign.DistributionType]autocodesign.AppCodesignAssets) error); ok {
		r0 = rf(codesignAssetsByDistributionType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
