// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	certificateutil "github.com/bitrise-io/go-xcode/certificateutil"
	mock "github.com/stretchr/testify/mock"
)

// CertificateProvider is an autogenerated mock type for the CertificateProvider type
type CertificateProvider struct {
	mock.Mock
}

// GetCertificates provides a mock function with given fields:
func (_m *CertificateProvider) GetCertificates() ([]certificateutil.CertificateInfoModel, error) {
	ret := _m.Called()

	var r0 []certificateutil.CertificateInfoModel
	if rf, ok := ret.Get(0).(func() []certificateutil.CertificateInfoModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]certificateutil.CertificateInfoModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
