// Code generated by mockery 2.9.4. DO NOT EDIT.

package autocodesign

import (
	appstoreconnect "github.com/bitrise-io/go-xcode/autocodesign/devportalclient/appstoreconnect"
	mock "github.com/stretchr/testify/mock"

	serialized "github.com/bitrise-io/go-xcode/xcodeproject/serialized"
)

// MockProfile is an autogenerated mock type for the Profile type
type MockProfile struct {
	mock.Mock
}

// Attributes provides a mock function with given fields:
func (_m *MockProfile) Attributes() appstoreconnect.ProfileAttributes {
	ret := _m.Called()

	var r0 appstoreconnect.ProfileAttributes
	if rf, ok := ret.Get(0).(func() appstoreconnect.ProfileAttributes); ok {
		r0 = rf()
	} else {
		r0, ok = ret.Get(0).(appstoreconnect.ProfileAttributes)
		if !ok {
		}
	}

	return r0
}

// BundleID provides a mock function with given fields:
func (_m *MockProfile) BundleID() (appstoreconnect.BundleID, error) {
	ret := _m.Called()

	var r0 appstoreconnect.BundleID
	if rf, ok := ret.Get(0).(func() appstoreconnect.BundleID); ok {
		r0 = rf()
	} else {
		r0, ok = ret.Get(0).(appstoreconnect.BundleID)
		if !ok {
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertificateIDs provides a mock function with given fields:
func (_m *MockProfile) CertificateIDs() (map[string]bool, error) {
	ret := _m.Called()

	var r0 map[string]bool
	if rf, ok := ret.Get(0).(func() map[string]bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0, ok = ret.Get(0).(map[string]bool)
			if !ok {
			}
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeviceIDs provides a mock function with given fields:
func (_m *MockProfile) DeviceIDs() (map[string]bool, error) {
	ret := _m.Called()

	var r0 map[string]bool
	if rf, ok := ret.Get(0).(func() map[string]bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0, ok = ret.Get(0).(map[string]bool)
			if !ok {
			}
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Entitlements provides a mock function with given fields:
func (_m *MockProfile) Entitlements() (serialized.Object, error) {
	ret := _m.Called()

	var r0 serialized.Object
	if rf, ok := ret.Get(0).(func() serialized.Object); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0, ok = ret.Get(0).(serialized.Object)
			if !ok {
			}
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ID provides a mock function with given fields:
func (_m *MockProfile) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0, ok = ret.Get(0).(string)
		if !ok {
		}
	}

	return r0
}
