package xcresult3

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/bitrise-io/go-steputils/v2/testreport"
	"github.com/bitrise-io/go-utils/v2/command"
	"github.com/bitrise-io/go-utils/v2/env"
	"github.com/stretchr/testify/require"
)

const sampleArtifactsGitURI = "https://github.com/bitrise-io/sample-artifacts.git"

var sampleArtifactsDir string

func TestMain(m *testing.M) {
	os.Exit(runTests(m))
}

func runTests(m *testing.M) int {
	dir, err := os.MkdirTemp("", "sample-artifacts-*")
	if err != nil {
		fmt.Printf("failed to create temp dir: %s\n", err)
		return 1
	}
	defer func(path string) {
		err := os.RemoveAll(path)
		if err != nil {
			fmt.Printf("failed to remove temp dir: %s\n", err)
		}
	}(dir)

	cmdFactory := command.NewFactory(env.NewRepository())
	cmd := cmdFactory.Create("git", []string{"clone", "--depth=1", sampleArtifactsGitURI, dir}, nil)
	if out, err := cmd.RunAndReturnTrimmedCombinedOutput(); err != nil {
		fmt.Printf("git clone failed: %s\n%s\n", err, out)
		return 1
	}

	sampleArtifactsDir = dir
	return m.Run()
}

// setupTestData copies an xcresult bundle from the cloned sample-artifacts repo
// into a per-test temp directory and returns the path to the copied bundle.
func setupTestData(t testing.TB, fileName string) string {
	t.Helper()

	srcPath := filepath.Join(sampleArtifactsDir, "xcresults", fileName)
	dstPath := filepath.Join(t.TempDir(), fileName)

	cmdFactory := command.NewFactory(env.NewRepository())
	cmd := cmdFactory.Create("cp", []string{"-r", srcPath, dstPath}, nil)
	out, err := cmd.RunAndReturnTrimmedCombinedOutput()
	require.NoError(t, err, "failed to copy test data: %s", out)

	return dstPath
}

// assertAttachmentProperties checks that props contain exactly expectedCount attachments,
// each with a sequentially numbered Name ("attachment_0", "attachment_1", ...) and a Value
// matching the pattern "<human-readable-name>_<nanosecond-timestamp>.<ext>".
// The human-readable part of the filename is generated by xcresulttool using the local
// timezone, and I don't see any guarantee that it is always assembled like this,
// so only the overall pattern is verified rather than the exact string.
func assertAttachmentProperties(t *testing.T, props *testreport.Properties, expectedCount int) {
	t.Helper()
	require.NotNil(t, props)
	require.Len(t, props.Property, expectedCount)
	for i, p := range props.Property {
		require.Equal(t, fmt.Sprintf("attachment_%d", i), p.Name)
		require.Regexp(t, `^.+_\d+\.\w+$`, p.Value)
	}
}

func TestConverter_XML(t *testing.T) {
	t.Run("xcresult3-flaky-with-rerun.xcresult", func(t *testing.T) {
		xcresultPath := setupTestData(t, "xcresult3-flaky-with-rerun.xcresult")
		t.Log("xcresultPath: ", xcresultPath)

		c := Converter{xcresultPth: xcresultPath}
		junitXML, err := c.Convert()
		require.NoError(t, err)

		// Save and nil out the timezone-dependent attachment properties before the
		// structural comparison; they are verified separately with assertAttachmentProperties.
		uiTestProps := junitXML.TestSuites[2].TestCases[0].Properties
		junitXML.TestSuites[2].TestCases[0].Properties = nil

		require.Equal(t, []testreport.TestSuite{
			{
				Name: "BullsEyeTests", Tests: 5, Failures: 0, Skipped: 0, Time: 0.9774,
				TestCases: []testreport.TestCase{
					{
						Name: "testStartNewRoundUsesRandomValueFromApiRequest()", ClassName: "BullsEyeFakeTests",
						Time: 0.014,
					},
					{
						Name: "testGameStyleCanBeChanged()", ClassName: "BullsEyeMockTests",
						Time: 0.0093,
					},
					{
						Name: "testScoreIsComputedPerformance()", ClassName: "BullsEyeTests",
						Time: 0.74,
					},
					{
						Name: "testScoreIsComputedWhenGuessIsHigherThanTarget()", ClassName: "BullsEyeTests",
						Time: 0.0041,
					},
					{
						Name: "testScoreIsComputedWhenGuessIsLowerThanTarget()", ClassName: "BullsEyeTests",
						Time: 0.21,
					},
				},
			},
			{
				Name: "BullsEyeSlowTests", Tests: 2, Failures: 0, Skipped: 0, Time: 0.53,
				TestCases: []testreport.TestCase{
					{
						Name: "testApiCallCompletes()", ClassName: "BullsEyeSlowTests",
						Time: 0.28,
					},
					{
						Name: "testValidApiCallGetsHTTPStatusCode200()", ClassName: "BullsEyeSlowTests",
						Time: 0.25,
					},
				},
			},
			{
				Name: "BullsEyeUITests", Tests: 1, Failures: 0, Skipped: 0, Time: 9,
				TestCases: []testreport.TestCase{
					{Name: "testGameStyleSwitch()", ClassName: "BullsEyeUITests", Time: 9},
				},
			},
			{
				Name: "BullsEyeFlakyTests", Tests: 3, Failures: 1, Skipped: 1, Time: 0.226,
				TestCases: []testreport.TestCase{
					{
						Name: "testFlakyFeature()", ClassName: "BullsEyeFlakyTests", Time: 0.2,
						Failure: &testreport.Failure{
							Value: `BullsEyeFlakyTests.swift:43: XCTAssertEqual failed: ("1") is not equal to ("0") - Number is not even`,
						},
					},
					{
						Name: "testFlakyFeature()", ClassName: "BullsEyeFlakyTests", Time: 0.006,
					},
					{
						Name: "testFlakySkip()", ClassName: "BullsEyeSkippedTests", Time: 0.02,
						Skipped: &testreport.Skipped{},
					},
				},
			},
		}, junitXML.TestSuites)

		assertAttachmentProperties(t, uiTestProps, 6)
	})

	t.Run("xcresults3 success-failed-skipped-tests.xcresult", func(t *testing.T) {
		xcresultPath := setupTestData(t, "xcresult3-success-failed-skipped-tests.xcresult")
		t.Log("xcresultPath: ", xcresultPath)

		c := Converter{xcresultPth: xcresultPath}
		junitXML, err := c.Convert()
		require.NoError(t, err)

		// Save and nil out the timezone-dependent attachment properties before the
		// structural comparison; they are verified separately with assertAttachmentProperties.
		failureProps := junitXML.TestSuites[0].TestCases[0].Properties
		junitXML.TestSuites[0].TestCases[0].Properties = nil

		require.Equal(t, []testreport.TestSuite{
			{
				Name:     "testProjectUITests",
				Tests:    3,
				Failures: 1,
				Skipped:  1,
				Time:     0.435,
				TestCases: []testreport.TestCase{
					{
						Name:      "testFailure()",
						ClassName: "testProjectUITests",
						Time:      0.26,
						Failure: &testreport.Failure{
							Value: "testProjectUITests.swift:30: XCTAssertTrue failed",
						},
					},
					{
						Name:      "testSkip()",
						ClassName: "testProjectUITests",
						Time:      0.086,
						Skipped:   &testreport.Skipped{},
					},
					{
						Name:      "testSuccess()",
						ClassName: "testProjectUITests",
						Time:      0.089,
					},
				},
			},
		}, junitXML.TestSuites)

		assertAttachmentProperties(t, failureProps, 3)
	})

	t.Run("xcresult3-multiple-test-plan-configurations.xcresult", func(t *testing.T) {
		xcresultPath := setupTestData(t, "xcresult3-multiple-test-plan-configurations.xcresult")
		t.Log("xcresultPath: ", xcresultPath)

		c := Converter{xcresultPth: xcresultPath}
		junitXML, err := c.Convert()
		require.NoError(t, err)
		require.NotNil(t, junitXML)

		require.EqualValues(
			t,
			junitXML.TestSuites[0].TestCases[0].Failure.Value,
			`English: swift_testingTests.swift:20: Expectation failed: true == false - // This test is intended to fail to demonstrate test failure reporting.
German: swift_testingTests.swift:20: Expectation failed: true == false - // This test is intended to fail to demonstrate test failure reporting.
`,
		)
	})
}

func BenchmarkConverter_XML(b *testing.B) {
	xcresultPath := setupTestData(b, "xcresult3-flaky-with-rerun.xcresult")
	b.Log("xcresultPath: ", xcresultPath)

	c := Converter{xcresultPth: xcresultPath}
	_, err := c.Convert()
	require.NoError(b, err)
}
