package xcodebuild

import (
	"reflect"
	"strings"
	"testing"
)

func TestCommandBuilder_cmdSlice(t *testing.T) {
	tests := []struct {
		name                              string
		projectPath                       string
		isWorkspace                       bool
		scheme                            string
		configuration                     string
		destination                       string
		forceDevelopmentTeam              string
		forceProvisioningProfileSpecifier string
		forceProvisioningProfile          string
		forceCodeSignIdentity             string
		disableCodesign                   bool
		disableIndexWhileBuilding         bool
		customBuildActions                []string
		archivePath                       string
		customOptions                     []string
		sdk                               string
		resultBundlePath                  string
		action                            Action
		want                              []string
	}{
		{
			name:                              "simulator",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "id=3222ioocsdcsa1",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"-destination",
				"id=3222ioocsdcsa1",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "generic iOS",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "generic/platform=iOS",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"-destination",
				"generic/platform=iOS",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "scheme",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "project_scheme",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"-scheme",
				"project_scheme",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "iphone simulator sdk",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "iphonesimulator12",
			action:                            BuildAction,
			want: []string{
				"",
				"build",
				"-sdk",
				"iphonesimulator12",
				"",
			},
		},
		{
			name:                              "analyze",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			resultBundlePath:                  "/tmp/Analyze.xcresult",
			action:                            AnalyzeAction,
			want: []string{
				"",
				"analyze",
				"-resultBundlePath",
				"/tmp/Analyze.xcresult",
				"",
			},
		},
		{
			name:                              "force development team",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "Bitrise",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"DEVELOPMENT_TEAM=Bitrise",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "force code sign identity",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "iOS Developer: Bitrise bot",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"CODE_SIGN_IDENTITY=iOS Developer: Bitrise bot",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "force profile",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "id 2331232",
			forceProvisioningProfile:          "id 2331232",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"PROVISIONING_PROFILE_SPECIFIER=id 2331232",
				"PROVISIONING_PROFILE=id 2331232",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "project",
			projectPath:                       "project.xcodeproj",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"-project",
				"project.xcodeproj",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "workspace",
			projectPath:                       "project.xcworkspace",
			isWorkspace:                       true,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"-workspace",
				"project.xcworkspace",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "debug configuration",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "debug",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"-configuration",
				"debug",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "archive",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "archive/path",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            ArchiveAction,
			want: []string{
				"",
				"archive",
				"-archivePath",
				"archive/path",
				"",
			},
		},
		{
			name:                              "disable index while building",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   false,
			disableIndexWhileBuilding:         true,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"COMPILER_INDEX_STORE_ENABLE=NO",
				"",
				"build",
				"",
			},
		},
		{
			name:                              "disable code signing",
			projectPath:                       "",
			isWorkspace:                       false,
			scheme:                            "",
			configuration:                     "",
			destination:                       "",
			forceDevelopmentTeam:              "",
			forceProvisioningProfileSpecifier: "",
			forceProvisioningProfile:          "",
			forceCodeSignIdentity:             "",
			disableCodesign:                   true,
			disableIndexWhileBuilding:         false,
			customBuildActions:                []string{""},
			archivePath:                       "",
			customOptions:                     []string{""},
			sdk:                               "",
			action:                            BuildAction,
			want: []string{
				"CODE_SIGNING_ALLOWED=NO",
				"",
				"build",
				"",
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := &CommandBuilder{
				projectPath:                       tt.projectPath,
				isWorkspace:                       tt.isWorkspace,
				scheme:                            tt.scheme,
				configuration:                     tt.configuration,
				destination:                       tt.destination,
				forceDevelopmentTeam:              tt.forceDevelopmentTeam,
				forceProvisioningProfileSpecifier: tt.forceProvisioningProfileSpecifier,
				forceProvisioningProfile:          tt.forceProvisioningProfile,
				forceCodeSignIdentity:             tt.forceCodeSignIdentity,
				disableCodesign:                   tt.disableCodesign,
				disableIndexWhileBuilding:         tt.disableIndexWhileBuilding,
				customBuildActions:                tt.customBuildActions,
				archivePath:                       tt.archivePath,
				customOptions:                     tt.customOptions,
				sdk:                               tt.sdk,
				resultBundlePath:                  tt.resultBundlePath,
				action:                            tt.action,
			}
			if got := c.args(); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("CommandBuilder.cmdSlice() = %v\nwant %v", strings.Join(got, "\n"), strings.Join(tt.want, "\n"))
			}
		})
	}
}
