// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	serialized "github.com/bitrise-io/go-xcode/v2/xcodeproject/serialized"
	mock "github.com/stretchr/testify/mock"
)

// BuildSettingsProvider is an autogenerated mock type for the BuildSettingsProvider type
type BuildSettingsProvider struct {
	mock.Mock
}

// TargetBuildSettings provides a mock function with given fields: projectPath, target, configuration, extraArgs
func (_m *BuildSettingsProvider) TargetBuildSettings(projectPath string, target string, configuration string, extraArgs ...string) (serialized.Object, error) {
	_va := make([]interface{}, len(extraArgs))
	for _i := range extraArgs {
		_va[_i] = extraArgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, projectPath, target, configuration)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TargetBuildSettings")
	}

	var r0 serialized.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, ...string) (serialized.Object, error)); ok {
		return rf(projectPath, target, configuration, extraArgs...)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, ...string) serialized.Object); ok {
		r0 = rf(projectPath, target, configuration, extraArgs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(serialized.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, ...string) error); ok {
		r1 = rf(projectPath, target, configuration, extraArgs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBuildSettingsProvider creates a new instance of BuildSettingsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuildSettingsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuildSettingsProvider {
	mock := &BuildSettingsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
