// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-xcode/v2/xcodeproject/serialized"
	mock "github.com/stretchr/testify/mock"
)

// NewBuildSettingsProvider creates a new instance of BuildSettingsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuildSettingsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuildSettingsProvider {
	mock := &BuildSettingsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuildSettingsProvider is an autogenerated mock type for the BuildSettingsProvider type
type BuildSettingsProvider struct {
	mock.Mock
}

type BuildSettingsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *BuildSettingsProvider) EXPECT() *BuildSettingsProvider_Expecter {
	return &BuildSettingsProvider_Expecter{mock: &_m.Mock}
}

// TargetBuildSettings provides a mock function for the type BuildSettingsProvider
func (_mock *BuildSettingsProvider) TargetBuildSettings(projectPath string, target string, configuration string, extraArgs ...string) (serialized.Object, error) {
	var tmpRet mock.Arguments
	if len(extraArgs) > 0 {
		tmpRet = _mock.Called(projectPath, target, configuration, extraArgs)
	} else {
		tmpRet = _mock.Called(projectPath, target, configuration)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TargetBuildSettings")
	}

	var r0 serialized.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, ...string) (serialized.Object, error)); ok {
		return returnFunc(projectPath, target, configuration, extraArgs...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, ...string) serialized.Object); ok {
		r0 = returnFunc(projectPath, target, configuration, extraArgs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(serialized.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, ...string) error); ok {
		r1 = returnFunc(projectPath, target, configuration, extraArgs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BuildSettingsProvider_TargetBuildSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetBuildSettings'
type BuildSettingsProvider_TargetBuildSettings_Call struct {
	*mock.Call
}

// TargetBuildSettings is a helper method to define mock.On call
//   - projectPath string
//   - target string
//   - configuration string
//   - extraArgs ...string
func (_e *BuildSettingsProvider_Expecter) TargetBuildSettings(projectPath interface{}, target interface{}, configuration interface{}, extraArgs ...interface{}) *BuildSettingsProvider_TargetBuildSettings_Call {
	return &BuildSettingsProvider_TargetBuildSettings_Call{Call: _e.mock.On("TargetBuildSettings",
		append([]interface{}{projectPath, target, configuration}, extraArgs...)...)}
}

func (_c *BuildSettingsProvider_TargetBuildSettings_Call) Run(run func(projectPath string, target string, configuration string, extraArgs ...string)) *BuildSettingsProvider_TargetBuildSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *BuildSettingsProvider_TargetBuildSettings_Call) Return(object serialized.Object, err error) *BuildSettingsProvider_TargetBuildSettings_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *BuildSettingsProvider_TargetBuildSettings_Call) RunAndReturn(run func(projectPath string, target string, configuration string, extraArgs ...string) (serialized.Object, error)) *BuildSettingsProvider_TargetBuildSettings_Call {
	_c.Call.Return(run)
	return _c
}
