// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewDirCreator creates a new instance of DirCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDirCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *DirCreator {
	mock := &DirCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DirCreator is an autogenerated mock type for the DirCreator type
type DirCreator struct {
	mock.Mock
}

type DirCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *DirCreator) EXPECT() *DirCreator_Expecter {
	return &DirCreator_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type DirCreator
func (_mock *DirCreator) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DirCreator_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type DirCreator_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *DirCreator_Expecter) MkdirAll(path interface{}, perm interface{}) *DirCreator_MkdirAll_Call {
	return &DirCreator_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *DirCreator_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *DirCreator_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DirCreator_MkdirAll_Call) Return(err error) *DirCreator_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DirCreator_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *DirCreator_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}
