// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUserProvider creates a new instance of UserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProvider {
	mock := &UserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserProvider is an autogenerated mock type for the UserProvider type
type UserProvider struct {
	mock.Mock
}

type UserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *UserProvider) EXPECT() *UserProvider_Expecter {
	return &UserProvider_Expecter{mock: &_m.Mock}
}

// CurrentUserName provides a mock function for the type UserProvider
func (_mock *UserProvider) CurrentUserName() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentUserName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserProvider_CurrentUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUserName'
type UserProvider_CurrentUserName_Call struct {
	*mock.Call
}

// CurrentUserName is a helper method to define mock.On call
func (_e *UserProvider_Expecter) CurrentUserName() *UserProvider_CurrentUserName_Call {
	return &UserProvider_CurrentUserName_Call{Call: _e.mock.On("CurrentUserName")}
}

func (_c *UserProvider_CurrentUserName_Call) Run(run func()) *UserProvider_CurrentUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserProvider_CurrentUserName_Call) Return(s string, err error) *UserProvider_CurrentUserName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserProvider_CurrentUserName_Call) RunAndReturn(run func() (string, error)) *UserProvider_CurrentUserName_Call {
	_c.Call.Return(run)
	return _c
}
