// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	autocodesign "github.com/bitrise-io/go-xcode/v2/autocodesign"

	mock "github.com/stretchr/testify/mock"

	profileutil "github.com/bitrise-io/go-xcode/v2/profileutil"
)

// ProvisioningProfileConverter is an autogenerated mock type for the ProvisioningProfileConverter type
type ProvisioningProfileConverter struct {
	mock.Mock
}

// ProfileInfoToProfile provides a mock function with given fields: info
func (_m *ProvisioningProfileConverter) ProfileInfoToProfile(info profileutil.ProvisioningProfileInfoModel) (autocodesign.Profile, error) {
	ret := _m.Called(info)

	if len(ret) == 0 {
		panic("no return value specified for ProfileInfoToProfile")
	}

	var r0 autocodesign.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(profileutil.ProvisioningProfileInfoModel) (autocodesign.Profile, error)); ok {
		return rf(info)
	}
	if rf, ok := ret.Get(0).(func(profileutil.ProvisioningProfileInfoModel) autocodesign.Profile); ok {
		r0 = rf(info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(autocodesign.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(profileutil.ProvisioningProfileInfoModel) error); ok {
		r1 = rf(info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProvisioningProfileConverter creates a new instance of ProvisioningProfileConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvisioningProfileConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProvisioningProfileConverter {
	mock := &ProvisioningProfileConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
