// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	profileutil "github.com/bitrise-io/go-xcode/v2/profileutil"
	mock "github.com/stretchr/testify/mock"
)

// ProvisioningProfileProvider is an autogenerated mock type for the ProvisioningProfileProvider type
type ProvisioningProfileProvider struct {
	mock.Mock
}

// ListProvisioningProfiles provides a mock function with given fields:
func (_m *ProvisioningProfileProvider) ListProvisioningProfiles() ([]profileutil.ProvisioningProfileInfoModel, error) {
	ret := _m.Called()

	var r0 []profileutil.ProvisioningProfileInfoModel
	if rf, ok := ret.Get(0).(func() []profileutil.ProvisioningProfileInfoModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]profileutil.ProvisioningProfileInfoModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
