// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	plistutil "github.com/bitrise-io/go-xcode/v2/plistutil"
	mock "github.com/stretchr/testify/mock"
)

// FileHandler is an autogenerated mock type for the FileHandler type
type FileHandler struct {
	mock.Mock
}

// Read provides a mock function with given fields: path
func (_m *FileHandler) Read(path string) (plistutil.PlistData, int, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 plistutil.PlistData
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (plistutil.PlistData, int, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) plistutil.PlistData); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plistutil.PlistData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(path)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Write provides a mock function with given fields: path, data, format
func (_m *FileHandler) Write(path string, data plistutil.PlistData, format int) error {
	ret := _m.Called(path, data, format)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, plistutil.PlistData, int) error); ok {
		r0 = rf(path, data, format)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFileHandler creates a new instance of FileHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileHandler {
	mock := &FileHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
