// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-xcode/v2/plistutil"
	mock "github.com/stretchr/testify/mock"
)

// NewFileHandler creates a new instance of FileHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileHandler {
	mock := &FileHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileHandler is an autogenerated mock type for the FileHandler type
type FileHandler struct {
	mock.Mock
}

type FileHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *FileHandler) EXPECT() *FileHandler_Expecter {
	return &FileHandler_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type FileHandler
func (_mock *FileHandler) Read(path string) (plistutil.PlistData, int, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 plistutil.PlistData
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (plistutil.PlistData, int, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) plistutil.PlistData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plistutil.PlistData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) int); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(path)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FileHandler_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type FileHandler_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - path string
func (_e *FileHandler_Expecter) Read(path interface{}) *FileHandler_Read_Call {
	return &FileHandler_Read_Call{Call: _e.mock.On("Read", path)}
}

func (_c *FileHandler_Read_Call) Run(run func(path string)) *FileHandler_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileHandler_Read_Call) Return(plistData plistutil.PlistData, n int, err error) *FileHandler_Read_Call {
	_c.Call.Return(plistData, n, err)
	return _c
}

func (_c *FileHandler_Read_Call) RunAndReturn(run func(path string) (plistutil.PlistData, int, error)) *FileHandler_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type FileHandler
func (_mock *FileHandler) Write(path string, data plistutil.PlistData, format int) error {
	ret := _mock.Called(path, data, format)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, plistutil.PlistData, int) error); ok {
		r0 = returnFunc(path, data, format)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileHandler_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type FileHandler_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - path string
//   - data plistutil.PlistData
//   - format int
func (_e *FileHandler_Expecter) Write(path interface{}, data interface{}, format interface{}) *FileHandler_Write_Call {
	return &FileHandler_Write_Call{Call: _e.mock.On("Write", path, data, format)}
}

func (_c *FileHandler_Write_Call) Run(run func(path string, data plistutil.PlistData, format int)) *FileHandler_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 plistutil.PlistData
		if args[1] != nil {
			arg1 = args[1].(plistutil.PlistData)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FileHandler_Write_Call) Return(err error) *FileHandler_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileHandler_Write_Call) RunAndReturn(run func(path string, data plistutil.PlistData, format int) error) *FileHandler_Write_Call {
	_c.Call.Return(run)
	return _c
}
